/* Generated by Edge Impulse
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_CLUSTERS_H_
#define _EI_CLASSIFIER_ANOMALY_CLUSTERS_H_

#include "edge-impulse-sdk/anomaly/anomaly.h"

// (before - mean) / scale
const float ei_classifier_anom_scale[EI_CLASSIFIER_ANOM_AXIS_SIZE] = { 0.04292169198994288, 0.10949665573481468, 0.10545365982753259 };
const float ei_classifier_anom_mean[EI_CLASSIFIER_ANOM_AXIS_SIZE] = { 0.4788766507849549, 0.18015896162074624, 0.1249575700384219 };

const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[EI_CLASSIFIER_ANOM_CLUSTER_COUNT] = { { { 0.35980474948883057, 1.1218376159667969, 1.2202167510986328 }, 1.070087545211513 }
, { { 1.2970563173294067, 0.34201639890670776, 0.7484614849090576 }, 1.2477668786757548 }
, { { 0.25763383507728577, -0.6468870043754578, -1.1029695272445679 }, 0.6549263170953109 }
, { { -0.028750307857990265, -1.4162625074386597, -1.1212064027786255 }, 0.5294602476383904 }
, { { -1.387864589691162, 1.2779641151428223, 0.8943620920181274 }, 1.6791169655858031 }
, { { 0.21060863137245178, 0.09753657877445221, -0.4568180441856384 }, 0.9112624415962225 }
, { { -0.6205185055732727, 0.08172740042209625, 0.6318313479423523 }, 0.9758457698367817 }
, { { -2.7774336338043213, -1.6453375816345215, -1.1849523782730103 }, 0 }
};

#endif // _EI_CLASSIFIER_ANOMALY_CLUSTERS_H_
